from pip.req import parse_requirements
import tarfile
from StringIO import StringIO

DOCKERFILE = """
FROM ubuntu:14.04
MAINTAINER Generated by parallel tests

RUN apt-get update -qqy 
RUN apt-get upgrade -qqy
RUN apt-get install -qqy python
RUN apt-get install -qqy python-pip python-dev
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

ENTRYPOINT ["/project/manage.py"]
"""


def create_context(requirements, tar_fileobj):
    tar_context = tarfile.TarFile(mode='w', fileobj=tar_fileobj)

    req = "\n".join(list(requirements))
    tar_info = tarfile.TarInfo(name="requirements.txt")
    tar_info.size = len(req)
    tar_context.addfile(tar_info, StringIO(req))

    tar_dockerfile_info = tarfile.TarInfo(name="Dockerfile")
    tar_dockerfile_info.size = len(DOCKERFILE)
    tar_context.addfile(tar_dockerfile_info, StringIO(DOCKERFILE))
    tar_context.close()


def get_requirements(requirements_file_name):
    requirements = set()
    if requirements_file_name:
        for req in parse_requirements(requirements_file_name):
            requirements.add(str(req.req))
    return requirements
